# Requires the Asset component and the Twig bundle
app.swagger_ui:
    path: /v1/api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# To expose your documentation as JSON
app.swagger:
    path: /v1/api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
